export const adventBoxes = [
  {
    number: 1,
    img: '/czechitas-advent-images/1.jpg',
    text: 'Venku je to jako hora a v chalupě jako voda.',
    open: false,
  },
  {
    number: 2,
    img: '/czechitas-advent-images/2.jpg',
    text: 'V jakém měsíci jsou Vánoce? ',
    open: false,
  },
  {
    number: 3,
    img: '/czechitas-advent-images/3.jpg',
    text: 'Jak se říká písním, které zpíváme na Vánoce?',
    open: false,
  },
  {
    number: 4,
    img: '/czechitas-advent-images/4.jpg',
    text: 'Jsme na obloze, jsou nás miliony. Planety však nejsme.. Co jsme? ',
    open: false,
  },
  {
    number: 5,
    img: '/czechitas-advent-images/5.jpg',
    text: 'Pod stromečkem na nás každoročně čeká? ',
    open: false,
  },
  {
    number: 6,
    img: '/czechitas-advent-images/6.jpg',
    text: 'Co se na Vánoce zdobí ozdobami a světýlky? ',
    open: false,
  },
  {
    number: 7,
    img: '/czechitas-advent-images/7.jpg',
    text: 'Jaké ovoce se rozkrajuje, abychom našli hvězdičku?',
    open: false,
  },
  {
    number: 8,
    img: '/czechitas-advent-images/8.jpg',
    text: 'V zimě dokonce i zebe. V létě je ho plné nebe. Na obzoru beránky, z rána jako za večera proměňuje červánky. Co je to? ',
    open: false,
  },
  {
    number: 9,
    img: '/czechitas-advent-images/9.jpg',
    text: 'Pošli vánoční pohled.',
    open: false,
  },
  {
    number: 10,
    img: '/czechitas-advent-images/10.jpg',
    text: 'Sněz tři šušenky.',
    open: false,
  },
  {
    number: 11,
    img: '/czechitas-advent-images/11.jpg',
    text: 'Napiš vánoční přání.',
    open: false,
  },
  {
    number: 12,
    img: '/czechitas-advent-images/12.jpg',
    text: 'Pozoruj noční oblohu.',
    open: false,
  },
  {
    number: 13,
    img: '//czechitas-advent-images/13.jpg',
    text: 'Zabal vánoční dárek',
    open: false,
  },
  {
    number: 14,
    img: '/czechitas-advent-images/14.jpg',
    text: 'Ukliď si svoje hračky.',
    open: false,
  },
  {
    number: 15,
    img: '/czechitas-advent-images/15.jpg',
    text: 'Vysřihni vločku z papíru.',
    open: false,
  },
  {
    number: 16,
    img: '/czechitas-advent-images/16.jpg',
    text: 'Přečti si pohádku.',
    open: false,
  },
  {
    number: 17,
    img: '/czechitas-advent-images/17.jpg',
    text: 'Najdi na obrázku dárek s mašlí.',
    open: false,
  },
  {
    number: 18,
    img: '/czechitas-advent-images/18.jpg',
    text: 'V Betlémě se narodil...',
    open: false,
  },
  {
    number: 19,
    img: '/czechitas-advent-images/19.jpg',
    text: 'Když zlobíme čert nám donese...',
    open: false,
  },
  {
    number: 20,
    img: '/czechitas-advent-images/20.jpg',
    text: 'Jaká zvířátka táhnou Santovi saně?',
    open: false,
  },
  {
    number: 21,
    img: '/czechitas-advent-images/21.jpg',
    text: 'V Americe nosí dárky někdo jiný než ježíšek, kdo to je?',
    open: false,
  },
  {
    number: 22,
    img: '/czechitas-advent-images/22.jpg',
    text: 'Kdo pomáhá Santovi a Ježíškovi balit vánoční dárky?',
    open: false,
  },
  {
    number: 23,
    img: '/czechitas-advent-images/23.jpg',
    text: 'Která země má jako první Štědrý den?',
    open: false,
  },
  {
    number: 24,
    img: '/czechitas-advent-images/24.jpg',
    text: 'Zazpívej si s námi vánoční koledu.',
    open: false,
  },
];
